/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package array.visualizer;

import static array.visualizer.ArrayVisualizer.BARS;
import static array.visualizer.ArrayVisualizer.CIRCULAR;
import static array.visualizer.ArrayVisualizer.DISPARITYDRAW;
import static array.visualizer.ArrayVisualizer.HOOPS;
import static array.visualizer.ArrayVisualizer.MESH;
import static array.visualizer.ArrayVisualizer.PIXELDRAW;
import static array.visualizer.ArrayVisualizer.PIXELS;
import static array.visualizer.ArrayVisualizer.POINTER;
import static array.visualizer.ArrayVisualizer.RAINBOW;
import static array.visualizer.ArrayVisualizer.SPIRALDRAW;
import static array.visualizer.ArrayVisualizer.VISUALS;
import static array.visualizer.ArrayVisualizer.currentLen;
import static array.visualizer.ArrayVisualizer.uf;

import javax.swing.JFrame;

/**
 *
 * @author S630690
 */
public class ViewPrompt extends javax.swing.JFrame implements AAFrame {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    JFrame f;

    /**
     * Creates new form ViewPrompt
     */
    public ViewPrompt(JFrame f) {
        this.f = f;
        setAlwaysOnTop(true);
        setUndecorated(true);
        initComponents();
        reposition();
        setVisible(true);
    }

    public void reposition(){
        setLocation(f.getX() + ((f.getWidth() - getWidth()) / 2), f.getY() + ((f.getHeight() - getHeight()) / 2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        barGraph = new javax.swing.JButton();
        dotGraph = new javax.swing.JButton();
        colorCircle = new javax.swing.JButton();
        triangleMesh = new javax.swing.JButton();
        spiral = new javax.swing.JButton();
        disparity = new javax.swing.JButton();
        disparityDots = new javax.swing.JButton();
        spiralDots= new javax.swing.JButton();
        rainbow = new javax.swing.JButton();
        hoops = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Select Visual Style");

        barGraph.setText("Bar Graph");
        barGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barGraphActionPerformed(evt);
            }
        });

        dotGraph.setText("Dot Graph");
        dotGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotGraphActionPerformed(evt);
            }
        });

        colorCircle.setText("Color Circle");
        colorCircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorCircleActionPerformed(evt);
            }
        });

        triangleMesh.setText("Triangle Mesh");
        triangleMesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triangleMeshActionPerformed(evt);
            }
        });

        spiral.setText("Spiral");
        spiral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spiralActionPerformed(evt);
            }
        });

        rainbow.setText("Rainbow");
        rainbow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rainbowActionPerformed(evt);
            }
        });

        disparity.setText("Disparity Circle");
        disparity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disparityActionPerformed(evt);
            }
        });

        hoops.setText("Hoops");
        hoops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoopsActionPerformed(evt);
            }
        });

        disparityDots.setText("Disparity Dots");
        disparityDots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disparityDotsActionPerformed(evt);
            }
        });

        spiralDots.setText("Spiral Dots");
        spiralDots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spiralDotsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER, true)
                .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, true)
                                .addComponent(barGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rainbow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(colorCircle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(disparity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(disparityDots, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, true)
                                .addComponent(dotGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(triangleMesh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spiral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hoops, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spiralDots, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER, true)
                        .addComponent(jLabel1))
                );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER, true)
                .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, true)
                                .addComponent(barGraph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dotGraph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, true)
                                .addComponent(rainbow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(triangleMesh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, true)
                                .addComponent(colorCircle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hoops, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, true)
                                .addComponent(disparity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spiral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, true)
                                .addComponent(disparityDots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spiralDots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addContainerGap(18, Short.MAX_VALUE))
                );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setAllFieldsFalse(){
        POINTER = false;
        DISPARITYDRAW = false;
        PIXELDRAW = false;
        RAINBOW = false;
        SPIRALDRAW = false;
    }

    private void barGraphActionPerformed(java.awt.event.ActionEvent evt) {
        setAllFieldsFalse();
        VISUALS = BARS;
        uf.jButton2ResetText();
        dispose();
    }
    private void dotGraphActionPerformed(java.awt.event.ActionEvent evt) {
        setAllFieldsFalse();
        VISUALS = PIXELS;
        uf.jButton2ResetText();
        dispose();
    }
    private void rainbowActionPerformed(java.awt.event.ActionEvent evt) {
        setAllFieldsFalse();
        VISUALS = BARS;
        RAINBOW = true;
        uf.jButton2ResetText();
        dispose();
    }
    private void triangleMeshActionPerformed(java.awt.event.ActionEvent evt) {
        setAllFieldsFalse();
        VISUALS = MESH;
        uf.jButton2ResetText();
        dispose();
    }
    private void colorCircleActionPerformed(java.awt.event.ActionEvent evt) {
        setAllFieldsFalse();
        VISUALS = CIRCULAR;
        RAINBOW = true;
        POINTER = true;
        if(currentLen == 2) currentLen = 4;
        uf.jButton2ResetText();
        dispose();
    }
    private void spiralActionPerformed(java.awt.event.ActionEvent evt) {
        setAllFieldsFalse();
        VISUALS = CIRCULAR;
        SPIRALDRAW = true;
        if(currentLen == 2) currentLen = 4;
        uf.jButton2ResetText();
        dispose();
    }
    private void disparityActionPerformed(java.awt.event.ActionEvent evt) {
        setAllFieldsFalse();
        VISUALS = CIRCULAR;
        DISPARITYDRAW = true;
        POINTER = true;
        if(currentLen == 2) currentLen = 4;
        uf.jButton2ResetText();
        dispose();
    }
    private void hoopsActionPerformed(java.awt.event.ActionEvent evt) {
        setAllFieldsFalse();
        VISUALS = HOOPS;
        uf.jButton2ResetText();
        dispose();
    }
    private void disparityDotsActionPerformed(java.awt.event.ActionEvent evt) {
        setAllFieldsFalse();
        VISUALS = CIRCULAR;
        DISPARITYDRAW = true;
        PIXELDRAW = true;
        if(currentLen == 2) currentLen = 4;
        uf.jButton2ResetText();
        dispose();
    }
    private void spiralDotsActionPerformed(java.awt.event.ActionEvent evt) {
        setAllFieldsFalse();
        VISUALS = CIRCULAR;
        SPIRALDRAW = true;
        PIXELDRAW = true;
        if(currentLen == 2) currentLen = 4;
        uf.jButton2ResetText();
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barGraph;
    private javax.swing.JButton dotGraph;
    private javax.swing.JButton colorCircle;
    private javax.swing.JButton triangleMesh;
    private javax.swing.JButton spiral;
    private javax.swing.JButton spiralDots;
    private javax.swing.JButton disparity;
    private javax.swing.JButton disparityDots;
    private javax.swing.JButton rainbow;
    private javax.swing.JButton hoops;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}